// Buffer configuration for gen_dsp Daisy wrapper
// Auto-generated by gen-dsp
//
// If your gen~ patch references buffers, their names are defined here.
// The WRAPPER_BUFFER_COUNT must match the number of defined buffer names.
// gen_dsp supports a maximum of 8 buffers.

#define WRAPPER_BUFFER_COUNT 0

// #define WRAPPER_BUFFER_NAME_0 array1
// #define WRAPPER_BUFFER_NAME_1 array2
// #define WRAPPER_BUFFER_NAME_2 array3
// #define WRAPPER_BUFFER_NAME_3 array4
// #define WRAPPER_BUFFER_NAME_4 array5
// #define WRAPPER_BUFFER_NAME_5 array6
// #define WRAPPER_BUFFER_NAME_6 array7
// #define WRAPPER_BUFFER_NAME_7 array8
