// gigaverb_engine.h - gen~ "gigaverb" bound to the generic GenEngine.
//
// GENERATED by scripts/gen_engine.py from gigaverb.json. The ParamId map below comes
// from the manifest's `knobs` (control name -> gen~ param); edit the manifest, not this
// file, then re-run `make gen-engine MANIFEST=...`. Preserved on re-run unless --force-glue.
//
// The export's wrapper_* C interface lives in namespace `gigaverb_daisy` (from -DDAISY_EXT_NAME=gigaverb):
//   Speed      -> 0 bandwidth [0..1]
//   Env        -> 1 damping [0..1]
//   Mix        -> 2 dry [0..1]
//   Pos        -> 4 revtime [0.1..1]
//   Size       -> 5 roomsize [0.1..300]
//   ModAmp     -> 7 tail [0..1]
//   Feedback   -> 6 spread [0..100]
//   EnvSize    -> 3 early [0..1]

#pragma once

#include "engine/iengine.h"
#include "_ext_daisy.h"            // namespace gigaverb_daisy { wrapper_* }; GenState == void
#include "engine/gen/gen_engine.h"

namespace spotykach {

struct GigaverbEngineWrap {
    static void* create(float sr, long block) {
        return gigaverb_daisy::wrapper_create(sr, block);
    }
    static void perform(void* st, float** in, long nin, float** out, long nout, long n) {
        gigaverb_daisy::wrapper_perform(st, in, nin, out, nout, n);
    }
    static int num_inputs()  { return gigaverb_daisy::wrapper_num_inputs(); }
    static int num_outputs() { return gigaverb_daisy::wrapper_num_outputs(); }

    // ParamId -> gen parameter index (-1 = unmapped).
    static int index_of(ParamId id) {
        switch (id) {
            case ParamId::Speed:        return 0;  // gen "bandwidth" [0..1]
            case ParamId::Env:          return 1;  // gen "damping" [0..1]
            case ParamId::Mix:          return 2;  // gen "dry" [0..1]
            case ParamId::Pos:          return 4;  // gen "revtime" [0.1..1]
            case ParamId::Size:         return 5;  // gen "roomsize" [0.1..300]
            case ParamId::ModAmp:       return 7;  // gen "tail" [0..1]
            case ParamId::Feedback:     return 6;  // gen "spread" [0..100]
            case ParamId::EnvSize:      return 3;  // gen "early" [0..1]
            default: return -1;
        }
    }

    // SIZE -> gigaverb "roomsize" scales the lengths of the reverb tank's delay lines, so a
    // raw write makes the delay taps jump and crackle on every knob step (and ADC jitter
    // passes straight through). Slew roomsize toward its target once per audio block (tick())
    // so it glides instead of stepping. set_param only stores the target; tick() does the write.
    static inline float s_room_cur    = 0.f;
    static inline float s_room_target = 0.f;
    static inline bool  s_room_primed = false;
    static constexpr float kRoomSlew  = 0.05f;   // per-block one-pole coefficient (~40 ms glide)

    static void set_param(void* st, ParamId id, DeckRef::Ref deck, float v01) {
        if (deck == DeckRef::B) return;  // single stereo effect: ignore deck B
        const int i = index_of(id);
        if (i < 0) return;
        const float lo = gigaverb_daisy::wrapper_param_min(st, i);
        const float hi = gigaverb_daisy::wrapper_param_max(st, i);
        const float val = lo + v01 * (hi - lo);
        if (id == ParamId::Size) {
            s_room_target = val;
            if (s_room_primed) return;        // tick() writes the slewed value
            s_room_cur = val; s_room_primed = true;  // snap on first set (boot/pickup seed)
        }
        gigaverb_daisy::wrapper_set_param(st, i, val);
    }

    // Called once per audio block by GenEngine: advance the slewed roomsize toward its target.
    static void tick(void* st) {
        if (!s_room_primed) return;
        const float d = s_room_target - s_room_cur;
        if (d > -1e-3f && d < 1e-3f) {       // close enough: snap and stop writing
            if (s_room_cur != s_room_target) {
                s_room_cur = s_room_target;
                gigaverb_daisy::wrapper_set_param(st, index_of(ParamId::Size), s_room_cur);
            }
            return;
        }
        s_room_cur += d * kRoomSlew;
        gigaverb_daisy::wrapper_set_param(st, index_of(ParamId::Size), s_room_cur);
    }

    static float get_param(void* st, ParamId id, DeckRef::Ref /*deck*/) {
        const int i = index_of(id);
        if (i < 0) return 0.f;
        const float lo  = gigaverb_daisy::wrapper_param_min(st, i);
        const float hi  = gigaverb_daisy::wrapper_param_max(st, i);
        const float val = gigaverb_daisy::wrapper_get_param(st, i);
        return (hi > lo) ? (val - lo) / (hi - lo) : 0.f;
    }
};

using GigaverbEngine = GenEngine<GigaverbEngineWrap>;

} // namespace spotykach
